Feat/subscription toggling
debtcollective/membership pull request #109
Opened 2019-10-18 12:35 UTC by castrolem

**What:**
User should be able to upgrade/downgrade their subscription

**Why:**
For users to increase or decrease their contribution without admin intervention
Closes #22 

**How:**
In the Subscription section in the back-office, User now has a Change Subscription button, that allows choosing from the existing plans a new plan (disabling his/her current plan from the selectable options)

## Screenshots
Logged as a user
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/1833858/67094128-6ce68f00-f1b3-11e9-8794-bfa4468ffc7a.png">

Available plans to select
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/1833858/67094137-707a1600-f1b3-11e9-9f1e-6143584fb540.png">

After choosing a different plan
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/1833858/67094149-766ff700-f1b3-11e9-91cb-2e9ed47119ba.png">

Profile after plan change was applied
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/1833858/67094528-54c33f80-f1b4-11e9-8b6d-385885a24acc.png">

2019-10-25 08:46 UTC, orlando requested changes
I have a few comments, but in general, looks good.

2019-10-25 08:46 UTC, orlando commented on app/controllers/plan_changes_controller.rb
> +    head :not_authorized unless current_user
What about moving this to a before_action method

2019-10-25 08:46 UTC, orlando commented on app/javascript/bundles/User/components/CurrentPlan.jsx
> +const CHANGE_PLAN_ENDPOINT = id => `/users/${id}/plan_changes`
I think this is good for now, but I'm not sure if we can use this library https://github.com/railsware/js-routes. Is a helper to have Rails routes in javascript. No need to change it now but let's keep it in mind in case we start doing this in multiple places

2019-10-25 08:46 UTC, orlando commented on app/jobs/toggle_user_active_subscription_plan_job.rb
> +    old_subscription.update(active: false)
@castrolem what about doing this inside a transaction? in case something fails we don't end up with multiple active subscriptions

2019-10-30 09:12 UTC, castrolem commented on app/javascript/bundles/User/components/CurrentPlan.jsx
> +const CHANGE_PLAN_ENDPOINT = id => `/users/${id}/plan_changes`
Added to my topics forest 🌳, good to keep in mind later.

2019-10-30 14:12 UTC, orlando approved these changes
LGTM

2019-10-30 14:15 UTC, merged