Feat/handle declined cards
debtcollective/membership pull request #164
Opened 2019-12-03 12:45 UTC by castrolem

**What:**
Notify the user when the card is declined or encounters a different error,
closes #161 

**Why:**
To give him/her the opportunity to refill the data and submit a new payment

**How:**
By adding error notifications

## Screenshots
|declined|insufficient funds|
|--|--|
|<img width="1430" alt="image" src="https://user-images.githubusercontent.com/1833858/70052053-b7409580-15d2-11ea-8623-dba4e605cdfe.png">|<img width="1435" alt="image" src="https://user-images.githubusercontent.com/1833858/70052193-0edf0100-15d3-11ea-832f-e0e14da3d98f.png">|

2019-12-03 17:01 UTC, orlando requested changes

2019-12-03 17:01 UTC, orlando commented on app/controllers/charges_controller.rb
> -    Raven.capture_message("We couldn't process payment for user_id: #{user.id}", extra: {params: params})
@castrolem this method looks exactly the same as https://github.com/debtcollective/fundraising/blob/3d981f61a7196ddb43c7340ac7cd346bd4f4551f/app/controllers/billings_controller.rb#L17. Can we move this method somewhere else instead?

This one looks that it has the same issue of the missing `if` statement, are we testing these flows correctly?

2019-12-03 17:01 UTC, orlando commented on app/controllers/charges_controller.rb
> +    e.message
@castrolem I don't think this is a good idea, we will be returning all the errors to the users instead of handling them properly. Let's rescue just the ones we expect and let Sentry notify us about other issues.

2019-12-03 17:01 UTC, orlando commented on app/controllers/charges_controller.rb
> +    e.message
@castrolem same as above, I'm not sure why we are catching all errors here.

2019-12-03 17:01 UTC, orlando commented on app/controllers/subscription_charges_controller.rb
> +    if customer.instance_of?(String)
@castrolem what about returning two variables (one for the customer and one for errors) instead of doing these type checks?

2019-12-04 16:48 UTC, castrolem commented on app/controllers/charges_controller.rb
> -    Raven.capture_message("We couldn't process payment for user_id: #{user.id}", extra: {params: params})
This is one is fine, it's creating a new user in stripe for this user if it doesn't have a `stripe_id` assigned to it.

2019-12-04 16:51 UTC, orlando commented on app/controllers/charges_controller.rb
> -    Raven.capture_message("We couldn't process payment for user_id: #{user.id}", extra: {params: params})
oh I see what the issues is, the `if` is at the end of the line, please move it to a `if block` if the line is this long.

2019-12-04 20:18 UTC, orlando approved these changes
There are a few things left to change but I don't want to block this anymore. Let's follow up later when working on the subscription_charges_controller

2019-12-04 20:18 UTC, merged