Feat/homepage
debtcollective/membership pull request #57
Opened 2019-09-02 10:16 UTC by castrolem

**What:**
Add homepage with plans and donation box

**Why:**
To have a landing page where users can see the benefits of donating.
Closes #1, closes #2 and closes #3

**How:**
By creating a static rendered page that loads the plans through react components.

2019-09-09 11:45 UTC, castrolem commented
## Screenshots
For some reason, I cannot take a full-page desktop screenshot with Chrome, it stretches the window and does not represent the actual sizing.

![localhost_3000_(iPhone 5_SE)](https://user-images.githubusercontent.com/1833858/64528085-eb742500-d307-11e9-8d66-0fe24bf89264.png)

2019-09-09 21:17 UTC, orlando requested changes

2019-09-09 21:17 UTC, orlando commented on app/assets/stylesheets/application.scss
> +html,
@castrolem How are we requiring all the files, I see we have a globals file, but what about using the `applications.scss` file to require all the other files in a certain order?

**application.scss**
```scss

@import 'globals';
@import 'footer';
...
```

2019-09-09 21:30 UTC, orlando commented
@castrolem there are also some issues regarding breakpoints.

![image](https://user-images.githubusercontent.com/849872/64567925-01411480-d31f-11e9-9f83-c9ff41786893.png)

Also, let's review the colors on a call, our background colors should look like the one we have in the community https://community.debtcollective.org/

2019-09-11 10:24 UTC, castrolem commented
@orlando fixed comments

2019-09-11 20:19 UTC, orlando approved these changes
LGTM :+1:

2019-09-11 22:50 UTC, merged